image:https://m-m-m.github.io/logo.svg[logo,width="150",link="https://m-m-m.github.io"]

image:https://img.shields.io/github/license/m-m-m/rpc.svg?label=License["Apache License, Version 2.0",link=https://github.com/m-m-m/rpc/blob/master/LICENSE]
image:https://travis-ci.com/m-m-m/rpc.svg?branch=master["build-status",link="https://travis-ci.com/m-m-m/rpc"]

== mmm-rpc

image:https://img.shields.io/maven-central/v/io.github.m-m-m/mmm-rpc.svg?label=Maven%20Central["Maven Central",link=https://search.maven.org/search?q=g:io.github.m-m-m]
image:https://m-m-m.github.io/javadoc.svg?status=online["apidoc",link="https://m-m-m.github.io/docs/api/io.github.mmm.rpc/module-summary.html"]

The module `mmm-rpc` provides an flexible and powerful solution for RPC (remote procedure calls).
Following the command-pattern you can implement custom `RpcRequests`s and call them asynchronous from any Java client including web-browsers via TeaVM. On the server-side you only need to implement a `RpcHandler` that handles your `RpcRequest` and produces the according result.

* support for different payload formats for free (switch between XML,YAML, or JSON or support all in parallel with no extra effort)
* type-safe, easy, asynchronous and reactive communication via HTTP2
* mimimum code for maximum outcome
* security build in by default (authorization, CSRF protection, etc.)

For motivation and details see the https://m-m-m.github.io/docs/api/io.github.mmm.rpc/module-summary.html[documnetation].

=== Usage

Maven Dependency:
```xml
<dependency>
  <groupId>io.github.m-m-m</groupId>
  <artifactId>mmm-rpc</artifactId>
</dependency>
```

Module Dependency:
```java
  requires transitive io.github.mmm.rpc;
```
